name: AkumaNoMi
version: ${project.version}
main: br.com.rafaelfaustini.akumanomi.AkumaNoMi
api-version: 1.16
authors: [ RafaelFaustini ]
website: rafaelfaustini.com.br
commands:
  merameranomi:
    description: Mera Mera no mi
    usage: /<command>
    aliases: ["meramera"]
  bounty:
    description: Manages the bounty list
    usage: /<command>
    aliases: [ "wanted", "procurado", "recompensa" ]